version: 1.4.0.{build}

branches:
  only:
  - appveyor2
  
clone_depth: 1

image: Ubuntu2004

skip_branch_with_pr: true
max_jobs: 1
# skip_non_tags: true

environment:
  matrix:
  - job_name: Build
    
  - job_name: BuildGUI
    job_depends_on: Build   
    
for:
 -
    matrix:
      only:
        - job_name: Build
          image: Ubuntu2004
    build_script:
        - chmod 755 win/appveyor_setup.sh
        - ./win/appveyor_setup.sh
        - export PATH="/home/appveyor/toolchains/mingw-w64-toolchain-9.1.0-linux-x86_64/mingw-w64-x86_64/bin:${PATH}"
        - cd /home/appveyor/projects/handbrake
        - ./configure --cross=x86_64-w64-mingw32 --harden --launch-jobs=$(nproc) --launch
        - cd build
        - make pkg.create.zip
    artifacts:
        - path: /home/appveyor/projects/handbrake/build/pkg/*.zip
          name: LibHandBrake
 -
    matrix:
      only:
        - job_name: BuildGUI
    image: Visual Studio 2019
    build_script:
        -  msbuild win\cs\build.xml /t:Nightly
    artifacts:
        - path: /home/appveyor/projects/handbrake/win/CS/HandBrakeWPF/bin/**/*
          name: HandBrakeGUI