version: 1.4.0.{build}

branches:
  only:
  - appveyor2
  
clone_depth: 1

image: Ubuntu2004

skip_branch_with_pr: true
max_jobs: 1
# skip_non_tags: true

environment:
  matrix:
  - job_name: Build
    
for:
 -
    matrix:
      only:
        - job_name: Build
          image: Ubuntu2004
    build_script:
        - sudo apt-get update -y
        - sudo apt-get install -y automake autoconf build-essential cmake curl gcc git intltool libtool libtool-bin m4 make nasm patch pkg-config python tar yasm zlib1g-dev ninja-build zip
        - sudo apt-get install -y bison bzip2 flex g++ gzip pax
        - sudo apt-get install -y python3-pip
        - sudo apt-get install -y python3-setuptools
        - sudo pip3 install meson
        - cd /home/appveyor/
        - wget https://github.com/bradleysepos/mingw-w64-build/releases/download/9.1.0/mingw-w64-toolchain-9.1.0-linux-x86_64.tar.gz
        - tar xvf mingw-w64-toolchain-9.1.0-linux-x86_64.tar.gz
        - export PATH="/home/appveyor/mingw-w64-toolchain-9.1.0-linux-x86_64/mingw-w64-x86_64/bin:${PATH}"
        - cd /home/appveyor/projects/handbrake
        - ./configure --cross=x86_64-w64-mingw32 --harden --launch-jobs=$(nproc) --launch
        - cd build
        - make pkg.create.zip
    artifacts:
        - path: /home/appveyor/projects/handbrake/build/libhb/hb.dll
          name: LibHandBrake
