version: 1.4.0

branches:
  only:
  - appveyor2
  
clone_depth: 1

image: Ubuntu2004

environment:
  matrix:

  - job_name: Build
    
  - job_name: BuildGUI
    job_depends_on: Build   

for:
    -
    matrix:
      only:
        - job_name: Build
          image: Ubuntu2004
          build_script:
          - sh: >-
            sudo apt-get install automake autoconf build-essential cmake curl gcc git intltool libtool libtool-bin m4 make nasm patch pkg-config python tar yasm zlib1g-dev ninja-build zip
            sudo apt-get install bison bzip2 flex g++ gzip pax
            sudo apt-get install python3-pip
            sudo apt-get install python3-setuptools
            sudo pip3 install meson
            cd /home/appveyor/
            wget https://github.com/bradleysepos/mingw-w64-build/releases/download/9.1.0/mingw-w64-toolchain-9.1.0-linux-x86_64.tar.gz
            tar xvf mingw-w64-toolchain-9.1.0-linux-x86_64.tar.gz
            export PATH="/home/appveyor/toolchains/mingw-w64-x86_64/bin:${PATH}"
            cd /home/appveyor/projects/handbrake
            ./configure --cross=x86_64-w64-mingw32 --enable-qsv --enable-vce --enable-nvenc --launch-jobs=$(nproc) --launch
            cd build
            make pkg.create.zip
          artifacts:
            - path: /home/appveyor/projects/handbrake/build/libhb/hb.dll
              name: LibHandBrake

    -
    matrix:
      only:
        - job_name: BuildGUI
          image: Visual Studio 2019
          build_script:
            -  msbuild win\cs\build.xml /t:Nightly

