name: macOS build

on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer

jobs:
  build:
    name: Build on macOS
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2

    - name: Toolchain Cache
      id: mac-toolchain
      uses: actions/cache@v2.1.4
      with:
        path: /usr/local
        key: mac-toolchain

    - name: Setup Environment
      if: steps.mac-toolchain.outputs.cache-hit != 'true'
      run: |
        scripts/mac-toolchain-build /usr/local

    - name: Build HandBrake
      run: |
        git submodule update --init --recursive
        ./configure
        cd build
        make ub && make pkg.create

    - name: Upload Assets
      uses: actions/upload-artifact@v2
      with:
        name: HandBrake-macos
        path: ./build/pkg
